name: Build Stub Mod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      - name: Make build dir
        run: mkdir -p build

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --config Release

      - name: Upload .so artifact
        uses: actions/upload-artifact@v4
        with:
          name: LevelBuilderAI-Stub
          path: build/*.so